### ISSUE TITLE
Missing FocalModulation import in fire-asufm/model/asufm/swin_block.py

### ISSUE THREAD

**Issue by sud-ril** [bronteee/fire-asufm#1]
@bronteee @bronte-audere 
I'm trying to reproduce the results by training on the given dataset and facing the following issue:

In the file fire-asufm/model/asufm/swin_block.py, the following import exists:

```python
from ..focalnet.focalnet import FocalModulation
```

However, FocalModulation is not present in the source code.

If FocalModulation is a required module, please include it in the source code or update the documentation to reflect the correct setup process. If the import path is incorrect, please provide the correct path.

Thank you for your assistance.

**Comment by ry-zakari** [comment]
Actuall i am facing same issue as i want to use the model as a baseline for my model. the file is missing.

**Comment by bronteee** [comment]
See [this commit](https://github.com/bronteee/fire-asufm/commit/e0a5a97843d13a5c7868d70c5849722e87ef9156) - let me know if you have any more issues.

**Comment by ry-zakari** [comment]
Thank you so much, It solved the issue of the focalnet file.
