### ISSUE TITLE
ModuleNotFoundError: No module named 'model.focalnet

### ISSUE THREAD

**Issue by ry-zakari** [bronteee/fire-asufm#2]
Hello, 

I am trying to use your model as one of my baseline or benchmarks, but I am facing error. it seems like a file is missing.

from ..focalnet.focalnet import FocalModulation

ModuleNotFoundError: No module named 'model.focalnet

Could you please update the code by proving the missing file. 

Thank you

**Comment by bronteee** [comment]
See [this commit](https://github.com/bronteee/fire-asufm/commit/e0a5a97843d13a5c7868d70c5849722e87ef9156).
