### ISSUE TITLE
W&B API: permission denied (<Response [403]>)

### ISSUE THREAD

**Issue by ry-zakari** [bronteee/fire-asufm#3]
Hello, 

when trying to run the main file an error happens. trying to access an  API, error below. 

wandb: Currently logged in as: anony-moose-164205501462235178. Use `wandb login --relogin` to force relogin
wandb: ERROR Error while calling W&B API: permission denied (<Response [403]>)
wandb: ERROR It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)

Thank you for your help and good work

**Comment by bronteli** [comment]
Hi, please see [here](https://docs.wandb.ai/ref/python/login) for W&B documentation on logging in - you will need your own account and API keys.
