### ISSUE TITLE
Error reproducing results 

### ISSUE THREAD

**Issue by ry-zakari** [bronteee/fire-asufm#4]
Hello, 

Actually i am trying so hard to re produce the results in your paper and make comparion. i was able to reached to the training steps. but from the results all validation are always 0s. please see screen shot and advice may be i am missing something. 

![image](https://github.com/user-attachments/assets/821a28af-78b9-42d8-a8ec-5c110f9b27f8)

**Comment by bronteee** [comment]
Hi, if you read [this line](https://github.com/bronteee/fire-asufm/blob/688dda94dec9e3b22f149f2b9335d3b38fd2277f/main.py#L64), you should be able to set the `skip_eval` parameter to `False`, which will perform validation.
